/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "ezbutwwaummegowbxwcr"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV6YnV0d3dhdW1tZWdvd2J4d2NyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODM0MzIzNjQsImV4cCI6MjA5OTAwODM2NH0.107z-nEN1ZVX3xHxz75vNyUOFQ-31QIDYNMHllZBvxk"